# Generated by Django 5.2.14 on 2026-05-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mood", models.CharField(max_length=50)),
                ("recommendation", models.TextField()),
            ],
        ),
    ]
